events {
    worker_connections 1024;
}

http {
    upstream flask_servers {
        # Load balancing com round-robin
        server flask1:5000;
        server flask2:5000;
    }

    server {
        listen 80;
        server_name 187.127.12.9;

        location / {
            proxy_pass http://flask_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /health {
            proxy_pass http://flask_servers/health;
        }
    }
}